name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    environment:
      name: Dockerhub
      url: https://hub.docker.com/r/45862391/powershell-container-demo
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker build
      run: docker build -t 45862391/powershell-container-demo:1.0.0 .

    - name: Docker push
      run: |
        echo "${{ secrets.DOCKERHUB_PWD }}" | docker login -u 45862391 --password-stdin
        docker push 45862391/powershell-container-demo:1.0.0
        docker logout